{% set version = "6.2_master" %}

package:
  name: anvio-minimal
  version: {{ version }}

source:
  git_url: https://github.com/merenlab/anvio
  git_rev: HEAD
  git_depth: 1 # shallow clone

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - bottle
    - pysam
    - ete3
    - scipy
    - scikit-learn
    - django
    - requests
    - psutil ==5.4.3
    - mistune
    - six
    - pandas ==0.25.1
    - matplotlib-base
    - statsmodels
    - colored
    - illumina-utils
    - tabulate
    - numba
    # these three are critical versions. any changes must be
    # tested with extra attention:
    - pyani ==0.2.10
    - cherrypy ==8.0.0
    - snakemake-minimal ==5.10.0
test:
  commands:
    - anvi-self-test --version
    - anvi-self-test --help

about:
  home: http://merenlab.org/software/anvio/index.html
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "An interactive analysis and visualization platform for omics data"
  dev_url:  https://github.com/merenlab/anvio
