{% set version = "6.1_master" %}

package:
  name: anvio-minimal
  version: {{ version }}

source:
  git_url: https://github.com/merenlab/anvio
  git_rev: HEAD
  git_depth: 1 # shallow clone

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    #This pins to an old snakeMake that predated 3.7
    - python ==3.6
    - numpy ==1.17.2
    - setuptools ==41.4.0
    - wheel ==0.33.6
    - pip ==20.0.2
  run:
    - python ==3.6
    - numpy ==1.17.1
    - bottle ==0.12.13
    - pysam ==0.15.2
    - ete3 ==3.1.1
    - scipy >=0.13.1
    - scikit-learn ==0.22.1
    - django ==2.2.5
    - cherrypy ==8.0.0
    - requests ==2.20.0
    - psutil ==5.4.3
    - mistune ==0.8.1
    - six ==1.11.0
    - pandas ==0.25.1
    - matplotlib ==2.2.3
    - pyani ==0.2.10
    - statsmodels ==0.9.0
    - snakemake ==5.10.0
    - colored ==1.3.93
    - illumina-utils ==2.7
    - tabulate ==0.8.3
    - numba ==0.48.0
test:
  commands:
    - anvi-self-test --version
    - anvi-self-test --help

about:
  home: http://merenlab.org/software/anvio/index.html
  license: GPL-3.0-or-later
  license_family: GPL3
  summary: "An interactive analysis and visualization platform for omics data"
  dev_url:  https://github.com/merenlab/anvio
