{% set version = "7" %}

package:
  name: anvio-minimal
  version: {{ version }}

source:
  git_url: https://github.com/merenlab/anvio
  git_tag: release-candidate

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - bottle
    - pysam
    - ete3
    - scipy
    # the following prevents an openmp error first reported in
    # merenlab/anvio#1489 that also occurs during conda bulid:
    # https://github.com/bioconda/bioconda-recipes/pull/26014#issuecomment-753693842
    - scikit-learn <0.21
    - django
    - requests
    - psutil ==5.4.3
    - mistune
    - six
    - pandas ==0.25.1
    - matplotlib-base
    - statsmodels
    - colored
    - illumina-utils
    - tabulate
    - numba
    - sqlite >=3.31.1
    - paste
    - vmatch
    # these three are critical versions. any changes must be
    # tested with extra attention:
    - pyani ==0.2.10
    - snakemake-minimal ==5.10.0
test:
  commands:
    - anvi-pan-genome --help
    - anvi-script-reformat-fasta --help

about:
  home: http://merenlab.org/software/anvio/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "An interactive analysis and visualization platform for omics data"
  dev_url:  https://github.com/merenlab/anvio

extra:
  container:
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: True
