#!/usr/bin/env python
# -*- coding: utf-8

import sys

import anvio

from anvio.errors import ConfigError, FilesNPathsError


__author__ = "Developers of anvi'o (see AUTHORS.txt)"
__copyright__ = "Copyleft 2015-2020, the Meren Lab (http://merenlab.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "A. Murat Eren"
__email__ = "a.murat.eren@gmail.com"
__description__ = ("Tabulates TAB-delmited data with headers in terminal: `cat table.txt | anvi-script-tabulate`")


def main(args):
    lines = []
    for line in sys.stdin:
        lines.append(line.strip('\n').split('\t'))

    anvio.TABULATE(lines[1:], lines[0])


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description=__description__)
    args = anvio.get_args(parser)

    try:
        main(args)
    except ConfigError as e:
        print(e)
        sys.exit(-1)
    except FilesNPathsError as e:
        print(e)
        sys.exit(-2)
