#!/usr/bin/env python
# -*- coding: utf-8

import sys

import anvio
import anvio.terminal as terminal

from anvio.contigops import GenbankToAnvio
from anvio.errors import ConfigError, FilesNPathsError


__author__ = "Developers of anvi'o (see AUTHORS.txt)"
__copyright__ = "Copyleft 2015-2018, the Meren Lab (http://merenlab.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "Mike Lee"
__email__ = "michael.lee0517@gmail.com"


run = terminal.Run()
progress = terminal.Progress()


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description="This script takes a GenBank file, and outputs a FASTA file, as well as two\
                                                  additional TAB-delimited output files for external gene calls and gene\
                                                  functions that can be used with the programs `anvi-gen-contigs-database`\
                                                  and `anvi-import-functions`.")

    parser.add_argument('-i', '--input-gb', action='store', required=True, help='Input GenBank file')
    parser.add_argument('--annotation-source', action='store', default='NCBI_PGAP', help='Annotation \
                             source (default: "NCBI_PGAP")')
    parser.add_argument("--annotation-version", action="store", default="v4.6", help='Annotation \
                             source version to be stored in the database (default: "v4.6")')
    parser.add_argument("--output-fasta", help='Output FASTA file path.')
    parser.add_argument("--output-gene-calls", help='Output file path for external gene calls')
    parser.add_argument("--output-functions", help="Output file path for anvi'o-importable gene functions file")

    args = anvio.get_args(parser)

    try:
        genbank_to_anvio = GenbankToAnvio(args)
        genbank_to_anvio.process()
    except ConfigError as e:
        print(e)
        sys.exit(-1)
    except FilesNPathsError as e:
        print(e)
        sys.exit(-2)
