#!/usr/bin/env python
# -*- coding: utf-8

import sys
import argparse

import anvio.db as db
import anvio.tables as t
import anvio.dbops as dbops
import anvio.terminal as terminal 

from anvio.errors import ConfigError


run = terminal.Run()
progress = terminal.Progress()

current_version = '5'
next_version    = '6'


def update_pan_db(pan_db_path, just_do_it = False):
    if pan_db_path is None:
        raise ConfigError("No database path is given.")

    # make sure someone is not being funny
    dbops.is_pan_db(pan_db_path)

    # make sure the version is accurate
    pan_db = db.DB(pan_db_path, None, ignore_version = True)
    if str(pan_db.get_version()) != current_version:
        raise ConfigError("Version of this pan database is not %s (hence, this script cannot really do anything)." % current_version)

    if not just_do_it:
        try:
            run.warning("This script will upgrade your pan database from v%s to v%s. We recently redesigned the way we keep clustering data in\
                         anvi'o pan and profile databases. After this everything will continue to work smootly (we hope). Well. You can just\
                         press ENTER to continue. If you want to cancel the upgrade and think more about it, press CTRL+C now. If you want to avoid\
                         this message the next time, use '--just-do-it'." % (current_version, next_version))
            input("Press ENTER to continue...\n")
        except:
            print()
            sys.exit()

    progress.new("Trying to upgrade the pan database")
    progress.update('...')

    pan_db.create_table(t.item_orders_table_name, t.item_orders_table_structure, t.item_orders_table_types)

    clusterings = pan_db.get_table_as_dict('clusterings')

    # set the version
    pan_db.remove_meta_key_value_pair('version')
    pan_db.set_version(next_version)

    for clustering in clusterings:
        clustering_name, distance, linkage = clustering.split(':')
        newick = clusterings[clustering]['newick']
        dbops.add_hierarchical_clustering_to_db(pan_db_path, clustering_name, newick, distance, linkage)

    # drop the old table and now irrelevant self values
    try:
        pan_db._exec('DROP TABLE clusterings;')
        pan_db.remove_meta_key_value_pair('available_clusterings')
        pan_db.remove_meta_key_value_pair('contigs_clustered')
        pan_db.remove_meta_key_value_pair('default_clustering')
    except:
        pass

    # commit
    try:
        pan_db._exec('COMMIT')
    except:
        pass

    # cleanup
    try:
        pan_db._exec('vacuum')
    except:
        pass

    # bye
    pan_db.disconnect()
    progress.end()

    run.info_single('Done! Your pan db is now %s.' % next_version)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='A simple script to upgrade pan database from version %s to version %s' % (current_version, next_version))
    parser.add_argument('pan_db', metavar = 'PAN_DB', help = "An anvi'o pan database of version %s" % current_version)
    parser.add_argument('--just-do-it', default=False, action="store_true", help = "Do not bother me with warnings")
    args = parser.parse_args()

    try:
        update_pan_db(args.pan_db, just_do_it = args.just_do_it)
    except ConfigError as e:
        print(e)
        sys.exit(-1)
