#!/usr/bin/env python
# -*- coding: utf-8

import sys
import argparse

import anvio.db as db
import anvio.tables as t
import anvio.dbops as dbops
import anvio.terminal as terminal

from anvio.errors import ConfigError


run = terminal.Run()
progress = terminal.Progress()

current_version = '20'
next_version    = '21'


def update_profile_db(profile_db_path, just_do_it = False):
    if profile_db_path is None:
        raise ConfigError("No database path is given.")

    # make sure someone is not being funny
    dbops.is_profile_db(profile_db_path)

    # make sure the version is accurate
    profile_db = db.DB(profile_db_path, None, ignore_version = True)
    if str(profile_db.get_version()) != current_version:
        raise ConfigError("Version of this profile database is not %s (hence, this script cannot really do anything)." % current_version)

    if not just_do_it:
        try:
            run.warning("This script will upgrade your profile database from v%s to v%s. We recently redesigned the way we keep clustering data in\
                         anvi'o pan and profile databases. After this everything will continue to work smootly (we hope). Well. You can just\
                         press ENTER to continue. If you want to cancel the upgrade and think more about it, press CTRL+C now. If you want to avoid\
                         this message the next time, use '--just-do-it'." % (current_version, next_version))
            input("Press ENTER to continue...\n")
        except:
            print()
            sys.exit()

    progress.new("Trying to upgrade the profile database")
    progress.update('...')

    try:
        profile_db.create_table(t.item_orders_table_name, t.item_orders_table_structure, t.item_orders_table_types)
    except:
        pass

    clusterings = profile_db.get_table_as_dict('clusterings')

    # move clustering data into the new table
    for clustering in clusterings:
        newick = clusterings[clustering]['newick']
        profile_db._exec('''INSERT INTO %s VALUES (?,?,?)''' % t.item_orders_table_name, tuple([clustering, 'newick', newick]))

    # update keys
    for old_key, new_key in [('available_clusterings', 'available_item_orders'),
                             ('contigs_clustered', 'contigs_ordered'),
                             ('default_clustering', 'default_item_order')]:
        try:
            profile_db.set_meta_value(new_key, profile_db.get_meta_value(old_key))
        except:
            pass

    # remove stuff that are not irrelevant
    try:
        profile_db._exec('DROP TABLE clusterings;')
        profile_db.remove_meta_key_value_pair('available_clusterings')
        profile_db.remove_meta_key_value_pair('contigs_clustered')
        profile_db.remove_meta_key_value_pair('default_clustering')
    except:
        pass

    # commit
    try:
        profile_db._exec('COMMIT')
    except:
        pass

    # cleanup
    try:
        profile_db._exec('vacuum')
    except:
        pass

    # set the version
    profile_db.remove_meta_key_value_pair('version')
    profile_db.set_version(next_version)

    # bye
    profile_db.disconnect()
    progress.end()

    run.info_single('Done! Your profile db is now %s.' % next_version)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='A simple script to upgrade profile database from version %s to version %s' % (current_version, next_version))
    parser.add_argument('profile_db', metavar = 'PROFILE_DB', help = "An anvi'o profile database of version %s" % current_version)
    parser.add_argument('--just-do-it', default=False, action="store_true", help = "Do not bother me with warnings")
    args = parser.parse_args()

    try:
        update_profile_db(args.profile_db, just_do_it = args.just_do_it)
    except ConfigError as e:
        print(e)
        sys.exit(-1)
