#!/usr/bin/env python
# -*- coding: utf-8

import sys

import anvio
import anvio.utils as utils
import anvio.terminal as terminal

from anvio.dbops import PanSuperclass
from anvio.errors import ConfigError, FilesNPathsError

__author__ = "Developers of anvi'o (see AUTHORS.txt)"
__copyright__ = "Copyleft 2015-2018, the Meren Lab (http://merenlab.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "A. Murat Eren"
__email__ = "a.murat.eren@gmail.com"
__description__ = "Add stacked bar layers of agnostos proportions to outside of gene-clusters in pangenome"


import argparse

from anvio.dbops import PanSuperclass

args = argparse.Namespace(pan_db="Enterococcus_faecalis/Enterococcus_faecalis-PAN.db", genomes_storage="Enterococcus-faecalis-GENOMES.db")

pan_db = PanSuperclass(args)

pan_db.init_gene_clusters()
pan_db.init_gene_clusters_functions()

# print(pan_db.gene_clusters_functions_dict['GC_00000212'])
print(pan_db.db.get_table_as_dataframe['gene_clusters'])
