#!/usr/bin/env python
# -*- coding: utf-8
"""Adds a DEAFULT collection with EVERYTHING in it into a profile database."""

import sys
import argparse

import anvio
import anvio.dbops as dbops
import anvio.terminal as terminal

from anvio.errors import ConfigError, FilesNPathsError


__author__ = "Developers of anvi'o (see AUTHORS.txt)"
__copyright__ = "Copyleft 2015-2018, the Meren Lab (http://merenlab.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "A. Murat Eren"
__email__ = "a.murat.eren@gmail.com"


pp = terminal.pretty_print
run = terminal.Run()
progress = terminal.Progress()


def main(args):
    dbops.is_profile_db(args.profile_db)

    profile_db = dbops.ProfileSuperclass(argparse.Namespace(profile_db=args.profile_db))

    collections_table = dbops.TablesForCollections(args.profile_db)
    collections_table.append('DEFAULT', {'EVERYTHING': profile_db.split_names})

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="A script to add a 'DEFAULT' collection in an anvi'o profile database with a bin\
                                                  'EVERYTHING' that describes all split names available in the profile databse")

    parser.add_argument(*anvio.A('profile-db'), **anvio.K('profile-db'))

    args = anvio.get_args(parser)

    try:
        main(args)
    except ConfigError as e:
        print(e)
        sys.exit(-1)
    except FilesNPathsError as e:
        print(e)
        sys.exit(-2)
