repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # About the `exclude` details: https://github.com/merenlab/anvio/pull/2580#issuecomment-4326877534
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      # TODO:
      #   This hook is disabled to keep the related PR smaller.
      #   Feel free to enable them when you are ready to tackle the changes.
      # - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^anvio/(data|tests)/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: ["--fix"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows
