channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-qvalue
  - biopython
  - blast
  - bottle
  - bowtie2
  - bwa
  - colored
  - diamond
  - django
  - ete3
  - famsa
  - fastani
  - fasttree
  - ghostscript
  - graphviz
  - hmmer
  - idba
  - illumina-utils
  - iqtree
  - matplotlib==3.5.1
  - mcl
  - megahit
  - meme
  - mistune
  - multiprocess
  - muscle=3.8.1551
  - networkx==3.1
  - nodejs
  - numba
  - numpy[version='<=1.24']
  - pandas==1.4.4
  - paste
  - plotext
  - prodigal
  - psutil
  - pulp==2.7.0
  - pyani
  - pymupdf
  - pysam
  - python=3.10
  - r-base
  - r-magrittr
  - r-optparse
  - r-stringi
  - r-tidyverse
  - reportlab
  - requests
  - rich-argparse
  - samtools[version='>=1.9']
  - scikit-learn==1.2.2
  - scipy
  - six
  - snakemake
  - spades
  - sqlite
  - statsmodels
  - tabulate
  - trimal
  - trnascan-se
  - vmatch
