[lint]
# https://docs.astral.sh/ruff/rules/
select = [
    # https://docs.astral.sh/ruff/rules/#isort-i
    "I",
    # https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid
    "TID",
    # https://docs.astral.sh/ruff/rules/utf8-encoding-declaration/
    "UP009",
    # https://docs.astral.sh/ruff/rules/trailing-whitespace/
    "W291",
]
