#!/usr/bin/env python
"""Compute a graph representation of a pangenome"""

import sys

import anvio
import anvio.panops as panops
import anvio.terminal as terminal

from anvio.errors import ConfigError, FilesNPathsError


__author__ = "Developers of anvi'o (see AUTHORS.txt)"
__copyright__ = "Copyleft 2015-2018, the Meren Lab (http://merenlab.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__authors__ = ['ahenoch', 'meren']
__requires__ = ['pan-db']
__can_use__ = ['genomes-storage-db', 'external-genomes']
__provides__ = ['pan-graph-db']
__description__ = ("An anvi'o program to compute a graph representation of pangenomes. It will do its magic, and store it into your "
                   "pan-db, or report a JSON formatted graph file, for downstream visualization and analyses with `anvi-display-pan-graph`")
__resources__ = []


@terminal.time_program
def main():
    args = get_args()

    try:
        pangraph = panops.PangenomeGraph(args)
        pangraph.process()
    except ConfigError as e:
        print(e)
        sys.exit(-1)
    except FilesNPathsError as e:
        print(e)
        sys.exit(-2)


def get_args():
    from anvio.argparse import ArgumentParser

    parser = ArgumentParser(description=__description__)

    groupA = parser.add_argument_group('INPUT', "Anvi'o artifacts for the pan graph to be computed.")
    groupA.add_argument(*anvio.A('pan-db'), **anvio.K('pan-db', {'required': True}))
    groupA.add_argument(*anvio.A('genomes-storage'), **anvio.K('genomes-storage', {'required': True}))
    groupA.add_argument(*anvio.A('external-genomes'), **anvio.K('external-genomes', {'required': True}))
    groupA.add_argument(*anvio.A('genomes-names'), **anvio.K('genomes-names', {'required': False}))

    groupB = parser.add_argument_group('OPTIONAL (BUT RECOMMENDED)DIAMOND USE', "Additional parameters controlling the "
                    "gene-endpoint fusion engine with scores coming from diamond. The additional parameters rarely need tuning; "
                    "defaults work well for most datasets. Adding diamond min-bit scores can increase accuracy of the gene "
                    "endpoints fusions into super-nodes. If you want to use a DIAMOND search-results file, the tool will "
                    "run on the pangenome gene-cluster membership alone and every cross-genome pair within a gene cluster "
                    "becomes an unweighted edge and the `minbit` ranking component is dropped.")

    groupB.add_argument(*anvio.A('diamond-search-results'), **anvio.K('diamond-search-results', {'required': False,
                    'help': "A DIAMOND tabular (outfmt 6) search-results file used to SCORE and WEIGHT the gene-cluster-derived edges."
                    "Can be generated by running anvi-pan-genome with the --intermediate-data-dir option. Candidate edges are "
                    "always defined by the pan-db gene clusters; if this file is provided, each cross-genome pair inside a gene "
                    "cluster is weighted by its reciprocal-averaged minbit and edges without a DIAMOND score are dropped (reproducing "
                    "the classic behavior exactly). If omitted, the tool runs on gene-cluster membership alone: every cross-genome pair "
                    "within a gene cluster becomes an unweighted edge and the `minbit` ranking component is dropped."}))
    groupB.add_argument('--minbit-floor', default=0.0, type=float, help = "Edges with minbit below this value are dropped "
                    "before ranking. Applied to the reciprocal-averaged minbit of each undirected cross-genome pair, this applies after"
                    "DIAMOND parsing has built the directed-pair dictionary. Use this for ranking quality control. This filter is analogous"
                    "to support-, decision- and uniqueness-floor filters running in the engine. If you are concerned about your enormous list"
                    "of DIAMOND hits, consider using the --minbit-prefilter parameter to reduce the dataset size before ranking.")
    groupB.add_argument('--minbit-prefilter', default=0.0, type=float, help = "Row-level minbit prefilter. Rows whose directed minbit "
                    "(bit_score / min(self_bit_u, self_bit_v)) is below this value are dropped before they enter the directed-pair dictionary. "
                    "The dictionary holds all surviving cross-genome directed pairs and can be tens of GB for large "
                    "pangenomes (e.g., 50+ genomes), which is the most common cause of OOM kills during the engine's parsing phase. "
                    "Distinct from --minbit-floor, which gates after reciprocal-average and is for ranking quality. 0 disables the "
                    "prefilter (default). Must be in [0.0, 1.0]. If you don't know which parameter is the correct one and you don't have OOM problems"
                    "use --minbit-floor.")

    groupC = parser.add_argument_group('OUTPUT', "Where the resulting pan-graph-db should be written. If you don't specify a path, "
                                "anvi'o will write the database into the current working directory using the project name as the "
                                "filename (i.e., './<project_name>-PAN-GRAPH.db').")
    groupC.add_argument(*anvio.A('output-file'), **anvio.K('output-file', {'required': False,
                                'help': "Output file path for the pan-graph-db this program will generate."}))
    groupC.add_argument(*anvio.A('tables-dir'), **anvio.K('tables-dir'))

    groupD = parser.add_argument_group('GRAPH BUILDING', "Controls how the gene-order graph is constructed from genome inputs.")

    groupD.add_argument('--min-contig-chain', default=5, type=int, help = "Skip contigs with fewer than this many genes "
                    "(filters very short/fragmented contigs).")
    groupD.add_argument('--max-contigs-per-component', default=1, type=int, help = "Cap on how many contigs (lines) "
                    "from a SINGLE genome are allowed to share one weakly-connected COMPONENT of the graph. During "
                    "fusion, a fuse that would union two components in a way that puts more than this many contigs from "
                    "any one genome into a single component is rejected (reason: `max-contigs-per-component`); the "
                    "excess contig is not dropped -- it stays free to join a different component that lacks its genome, "
                    "or ends up as its own component. -1 (default) disables the cap and preserves the classic behavior "
                    "where a genome may thread arbitrarily many of its contigs through one component. Set it to 1 for "
                    "CLOSED/complete genomes, where each genome should contribute at most one contig per replicon and a "
                    "second one signals a spurious cross-replicon fusion. WARNING: a low cap will fragment DRAFT "
                    "genomes, since a fragmented chromosome legitimately spreads many contigs across the same "
                    "component; each excess contig then becomes a separate component. Must be -1 or a positive integer.")
    groupD.add_argument('--no-remerge', default=False, action='store_true',
                    help = "Skip the post-engine remerge pass. By default (no flag), anvi'o walks every parent "
                    "gene cluster that produced multiple synteny clusters and merges pairs that look like "
                    "engine over-splits: same weakly connected component, not in-series in the DAG, and "
                    "disjoint genome coverage. Pass this flag to disable that pass and keep the engine's "
                    "original splits intact.")
    groupD.add_argument('--remerge-max-length', default=10, type=int,
                    help = "Asymmetry cap (in DAG edges) for remerge candidates. For each candidate pair, "
                    "the remerge pass measures shortest-path distances from BOTH the lowest common ancestor "
                    "(LCA) and the lowest common descendant (LCD), where they exist, to each of the two "
                    "nodes. If either |dist_a - dist_b| exceeds this value the merge is rejected. This "
                    "blocks topologically lopsided merges where one candidate sits much deeper/shallower "
                    "than the other relative to the shared ancestor or descendant. -1 disables the check."
                    "When only one of LCA or LCD exists, only that side's check applies; pairs with "
                    "neither (extremely rare on a connected DAG) are not rejected by this guard.")
    groupD.add_argument('--no-include-non-coding-genes', default=False, action='store_true',
                    help = "Drop non-coding gene calls (rRNA, tRNA, etc.) from the graph. By default (no flag), "
                    "non-coding gene calls are kept as singleton super-nodes typed `rna`. Non-coding genes are "
                    "detected via each genome's CONTIGS.db `call_type` column (anything that is not CODING). "
                    "They have no DIAMOND hits (DIAMOND runs on translated proteins) and therefore never merge "
                    "across genomes -- each non-coding gene becomes its own node. Pass this flag to drop them "
                    "before component-id and layout computation; flanking gene-order edges are re-stitched so "
                    "line continuity is preserved.")

    groupE = parser.add_argument_group('PANGENOME GRAPH ENGINE PARAMETERS', "Parameters controlling the gene-endpoint fusion engine. "
                    "These rarely need tuning; defaults work well for most datasets.")

    groupE.add_argument('--locality-window', default=10, type=int, help = "Flanking window size (in genes) on each side of a candidate "
                    "line pair, used to decide whether two contigs are co-oriented or flipped.")
    groupE.add_argument('--min-window-completeness', default=0, type=int, help = "Minimum number of genes that each of the four flanking "
                    "windows (left/right of each endpoint) must contain for an edge to CONTRIBUTE TO ORIENTATION SCORING. Must be "
                    "0..--locality-window (0 disables the filter). SOFT gate -- it does NOT prevent fusion: an edge whose any flanking "
                    "window is shorter than this is dropped from the orientation/locality scan only, NOT from the fusion pool. Its "
                    "`decision` ranking component instead falls back to `--decision-boundary-score` (if its line pair still receives a "
                    "same/flip label) or `--decision-tie-score` (if not), both 0.0 by default. Because the edge survives, the two "
                    "lines can still fuse when `--decision-floor` is 0.0 and `--ranking-mean` is arithmetic (a zeroed component only "
                    "lowers the arithmetic mean; under geometric mean it drives the whole score to 0). To hard-drop such edges, raise "
                    "`--decision-floor` above 0.")
    groupE.add_argument('--min-line-pair-hits', default=50, type=int, help = "Orientation-side gate. Minimum number of edges (DIAMOND "
                    "hits) between two contig lines required for the pair to receive a same/flip orientation label. SOFT gate -- it "
                    "does NOT prevent fusion: a pair with fewer hits simply gets NO orientation label, which only makes its edges take "
                    "`--decision-tie-score` (default 0.0) as their `decision` ranking component. The edges are NOT removed from the "
                    "fusion pool, so such a pair can still fuse: with `--decision-floor 0.0` the zeroed decision passes the floor, and "
                    "under `--ranking-mean arithmetic` the combined score can still clear `--min-ranking-score` on the strength of the "
                    "other components (under geometric mean a zeroed component drives the whole score to 0, excluding the edge unless "
                    "`--min-ranking-score` is also 0). To HARD-BLOCK under-supported line pairs from fusing use "
                    "`--fusion-min-line-pair-hits`; to require a non-zero decision score raise `--decision-floor`.")
    groupE.add_argument('--fusion-min-line-pair-hits', default=0, type=int, help = "Fusion-side hard cutoff. Line pairs with fewer than "
                    "this many edges are dropped from the ranking pool entirely and NEVER fused (alongside the existing "
                    "same-genome-conflict and transitive-cycle guards). Independent of --min-line-pair-hits, which only gates "
                    "orientation labeling: set this above 0 if you want under-supported line pairs to be excluded from fusion "
                    "regardless of how the ranking otherwise scores them. A potential usecase is plasmids in the dataset. "
                    "0 disables the cutoff.")
    groupE.add_argument('--orientation-tie-threshold', default=0.35, type=float, help = "Score margin under which a line-pair orientation "
                    "call is treated as a tie and demoted (see --orientation-demotion-strategy). SOFT -- it does NOT prevent fusion: a "
                    "tied/demoted pair simply loses its same/flip label, so its edges fall back to `--decision-tie-score` (default 0.0) "
                    "for the `decision` ranking component instead of being removed from the fusion pool. As with `--min-line-pair-hits`, "
                    "such edges can still fuse when `--decision-floor` is 0.0 and `--ranking-mean` is arithmetic.")
    groupE.add_argument('--min-orientation-score', default=0.5, type=float, help = "Minimum orientation score for a line pair to receive "
                    "a same/flip label. SOFT -- it does NOT prevent fusion: pairs below this are dropped from ORIENTATION LABELING "
                    "only, not from the fusion pool. Their edges fall back to `--decision-tie-score` (default 0.0) for the `decision` "
                    "ranking component, so with `--decision-floor 0.0` and `--ranking-mean arithmetic` they can still fuse on the "
                    "strength of the other components. Use `--fusion-min-line-pair-hits`, or raise `--decision-floor`, for a hard cutoff.")
    groupE.add_argument('--orientation-demotion-strategy', default='slimmest-margin',
                    choices=['slimmest-margin', 'fewest-edges'], help = "How to break ties when committing line-pair "
                    "orientations during the spanning-tree walk.")
    groupE.add_argument('--ranking-components', default='minbit,decision,support,uniqueness', type=str, help = "Comma-separated list "
                    "of components used to rank edges before fusion (any subset of minbit, decision, support, uniqueness). "
                    "'uniqueness' (opt-in; not in the default) is min(uniqueness(u), uniqueness(v)) where uniqueness(g) = "
                    "partner_genomes(g) / hit_count(g). The number of distinct genomes among g's cross-genome DIAMOND partners "
                    "divided by the total partner count (gated by GC in panmode). Any single-copy gene scores 1.0 regardless of "
                    "how core it is; multi-copy GCs score below 1.0; capped at 1.0 by construction. NOTE: `minbit` requires "
                    "`--diamond-search-results`; when no DIAMOND file is provided it is silently dropped from this list (edges are "
                    "unweighted) and the remaining components are used.")
    groupE.add_argument('--ranking-mean', default='geometric', choices=['geometric', 'arithmetic'], help = "Mean used to "
                    "combine ranking components into a single score per edge.")
    groupE.add_argument('--decision-floor', default=0.0, type=float, help = "Edges whose per-edge decision_score (the locality-window "
                    "top-n mean selected by the line-pair orientation label) is below this value are dropped before fusion. Applied "
                    "at ranking time, as soon as the decision score is available; analogous to --minbit-floor for raw minbit. "
                    "Must be in [0.0, 1.0]; all ranking-component scores are clamped to that range in the engine.")
    groupE.add_argument('--support-floor', default=0.0, type=float, help = "Edges whose line-pair support (n_edges between the two "
                    "lines divided by min(len(line_a), len(line_b))) is below this value are dropped before fusion. Applied at "
                    "ranking time; analogous to --minbit-floor for raw minbit. Must be in [0.0, 1.0]; all ranking-component scores "
                    "are clamped to that range in the engine, so a line pair with more edges than the shorter line has genes "
                    "saturates at support=1.0.")
    groupE.add_argument('--uniqueness-floor', default=0.0, type=float, help = "Edges whose per-edge uniqueness "
                    "(min(uniqueness(u), uniqueness(v)) where uniqueness(g) = partner_genomes(g) / hit_count(g); gated by GC in "
                    "panmode) is below this value are dropped before fusion. Applied at ranking time; analogous to --minbit-floor "
                    "for raw minbit. Any single-copy gene edge scores 1.0, so a floor of e.g. 0.5 keeps edges only when both "
                    "endpoints have at most ~2 partners per genome. Use this to exclude edges anchored on promiscuous genes "
                    "(transposases, mobile elements, etc.) regardless of how uniqueness is weighted in --ranking-components.")
    groupE.add_argument('--decision-tie-score', default=0.0, type=float, help = "Decision score assigned to edges whose "
                    "line pair has NO orientation label -- i.e. pairs that are tied (`--orientation-tie-threshold`), too weak "
                    "(`--min-orientation-score`), under-supported (`--min-line-pair-hits`), or demoted by the odd-cycle resolver. "
                    "Pair-level fallback: no fwd-vs-rev preference exists, so this value replaces the missing `decision` component "
                    "in the ranking. It defaults to 0.0, which zeroes the decision component WITHOUT removing the edge -- so with "
                    "`--decision-floor 0.0` and `--ranking-mean arithmetic` the pair can still fuse (under geometric mean a 0 here "
                    "drives the whole score to 0). Set it above 0 to let unlabeled pairs contribute a non-zero decision score.")
    groupE.add_argument('--decision-boundary-score', default=0.0, type=float, help = "Decision score assigned to edges in "
                    "confidently labeled pairs (same/flip) whose specific edge couldn't be scored by the locality scan, "
                    "typically because one or both endpoint genes sit at contig boundaries (empty flanking window) or because "
                    "--min-window-completeness dropped the edge from the orientation scan. Per-edge fallback on an otherwise good "
                    "pair: it defaults to 0.0, which zeroes that edge's `decision` component WITHOUT removing the edge, so with "
                    "`--decision-floor 0.0` and `--ranking-mean arithmetic` the edge can still fuse on the strength of the other "
                    "components. Set it above 0.0 to keep such contig-end edges in well-oriented pairs from being zeroed out in "
                    "the ranking.")
    groupE.add_argument('--min-ranking-score', default=0.1, type=float, help = "Edges whose combined ranking score (the mean of "
                    "--ranking-components) is below this value are skipped during fusion. Independent of --minbit-floor, which gates "
                    "on raw minbit; this gates on the aggregated score.")
    groupE.add_argument('--fusion-top-bucket-k', default=1, type=int, help = "Number of top-ranked edges sampled per fusion step "
                    "(Prim-style frontier growth with stochastic top-K bucketing).")
    groupE.add_argument('--fusion-seed', default=42, type=int, help = "Random seed for the stochastic top-K fusion sampler.")
    groupE.add_argument('--region-scope', default='component', choices=['global', 'component'], help = "Scope of what is considered "
                    "present in all genomes during region classification (backbone vs. variable) and the normalized region metrics. "
                    "'global' (default) counts genomes across the entire pangenome -- a region is BR only if every genome in "
                    "the pangenome reaches it. 'component' counts only the genomes present in the current weakly-connected "
                    "component -- a region is BR relative to the genomes that actually appear in its component, which treats "
                    "each component as an independent sub-pangenome. With 'component' a 1-genome component is trivially classified "
                    "as backbone; pick 'global' if that's not the intent.")

    groupF = parser.add_argument_group('LAYOUT & SIMPLIFICATION', "Controls how the graph is compressed and long edges are filtered.")

    groupF.add_argument('--component', default='CP_0001', type=str, help = "Which weakly connected component to lay out and summarize. "
                    "Components are named largest-first as 'CP_0001', 'CP_0002', ...; the default ('CP_0001') selects the largest. All "
                    "components are still persisted in the pan-graph-db.")
    groupF.add_argument('--gene-cluster-grouping-threshold', default=-1, type=int, help = "Compress linear chains of nodes of "
                    "this length or longer into groups (-1 disables grouping; useful to simplify long conserved runs).")
    groupF.add_argument('--grouping-compression', default=1.0, type=float, help = "Compression factor for grouped chains "
                    "(1.0 = no compression; lower values squeeze grouped nodes closer in the layout).")
    groupF.add_argument('--max-edge-length-filter', default=-1, type=int, help = "Remove edges longer than this length threshold "
                    "after layout (-1 disables filtering; lower values prune long jumps/repeats).")

    groupG = parser.add_argument_group('METADATA & LAYERS', "Display and metadata options for the resulting pan-graph.")

    groupG.add_argument(*anvio.A('description'), **anvio.K('description'))
    groupG.add_argument(*anvio.A('project-name'), **anvio.K('project-name'))
    groupG.add_argument('--load-state', default='default', type=str, help="Initial display state name to store/use in the pan-graph-db.")
    groupG.add_argument('--import-values', default='start,stop,partial,call_type', type=str, help = "Comma-separated "
                    "numeric columns from the pangenome table to copy as node layers (e.g., start, stop, partial); "
                    "non-numeric/missing columns are ignored.")

    groupH = parser.add_argument_group('ROBUSTNESS & DEBUGGING', "Controls safety checks and noisy-data handling.")

    groupH.add_argument('--just-do-it', default=False, action="store_true", help = "Bypass safety checks (e.g., "
                    "over-splitting) and continue even when warnings would normally abort; use to diagnose tough datasets.")

    return parser.get_args(parser)


if __name__ == '__main__':
    main()
