# -*- coding: utf-8

import os
import argparse
import pandas as pd

import anvio
import anvio.workflows as w
import anvio.terminal as terminal
import anvio.filesnpaths as filesnpaths

from anvio.workflows.phylogenomics import PhylogenomicsWorkflow

__copyright__ = "Copyleft 2015-2024, The Anvi'o Project (http://anvio.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "Alon Shaiber"
__email__ = "alon.shaiber@gmail.com"

run = terminal.Run()

this_workflow_is_inherited_by_another = (
    False
    if "anvio/workflows/phylogenomics" in str(workflow.included[0].abspath())
    else True
)
if not this_workflow_is_inherited_by_another:
    # don't be confused, child. when things come to this point, the variable `config`
    # is already magically filled in by snakemake:
    M = PhylogenomicsWorkflow(
        argparse.Namespace(
            config=config,
            this_workflow_is_inherited_by_another=this_workflow_is_inherited_by_another,
        )
    )
    M.init()
    dirs_dict = M.dirs_dict

    include: w.get_workflow_snake_file_path("contigs")


rule phylogenomics_target_rule:
    """Collect the expected phylogenomics workflow outputs."""
    input:
        targets=M.get_phylogenomics_target_files(),


# Workflow rule modules. Keep this order to preserve existing rule dependencies.
include: w.get_workflow_rule_file_path("phylogenomics", "main.smk")


if "anvio/workflows/phylogenomics" in str(workflow.included[0].abspath()):
    # check if all program dependencies are met. for this line to be effective,
    # there should be an initial dry run step (which is the default behavior of
    # the `WorkflowSuperClass`, so you are most likely covered).
    M.check_workflow_program_dependencies(workflow)
