# -*- coding: utf-8

"""Snakemake file for the metagenomics worklfow.

See the online documentation for the jargon, and
how to use it.
"""

import os
import anvio
import argparse
import pandas as pd
import anvio.utils as u
import anvio.workflows as w
import anvio.dbops as dbops
import anvio.terminal as terminal
import anvio.filesnpaths as filesnpaths

from anvio.errors import ConfigError, FilesNPathsError
from anvio.workflows.metagenomics import MetagenomicsWorkflow
from anvio.tables.miscdata import TableForLayerAdditionalData

__copyright__ = "Copyleft 2015-2024, The Anvi'o Project (http://anvio.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "Alon Shaiber"
__email__ = "alon.shaiber@gmail.com"

run = terminal.Run()
progress = terminal.Progress()

this_workflow_is_inherited_by_another = (
    False
    if "anvio/workflows/metagenomics" in str(workflow.included[0].abspath())
    else True
)

if not this_workflow_is_inherited_by_another:
    # it is important that this comes before the include statement since
    # M is defined here and will also be used in the contigs workflow
    M = MetagenomicsWorkflow(argparse.Namespace(config=config))
    M.init()
    dirs_dict = M.dirs_dict

    # in order to generate the contigs databases we include the snakefile
    # for the generation of contigs databases
    include: w.get_workflow_snake_file_path("contigs")


# SR/LR assembler availability from the workflow class
available_sr, available_lr = M.get_assembly_software_list()

# Which assemblers are enabled in the config?
sr_enabled = [
    a for a in available_sr if M.get_param_value_from_config([a, "run"]) is True
]
lr_enabled = [
    a for a in available_lr if M.get_param_value_from_config([a, "run"]) is True
]

sr_count = len(sr_enabled)
lr_count = len(lr_enabled)

# Enforce assembler selection by read type (SR vs LR)
if not M.references_mode:
    # If SR data exists, require exactly one SR assembler
    if M.has_sr and sr_count == 0:
        raise WorkflowError(
            f"You didn't specify any assembler for your short-reads metagenomes and yet "
            f"you config file shows that you are not using references_mode. If you already "
            f"have your assemblies or reference fasta files, then maybe you need to add "
            f'\'"references_mode": true, and a \'"fasta_txt: "name-of-your-fasta-txt-file" '
            f"to your config file. Otherwise, if you do mean to use assembly, please set "
            f"'run: true' for one of the following available short-read assembler: {available_sr})."
        )
    if sr_count > 1:
        raise WorkflowError(
            f"Multiple short-reads assemblers are enabled; enable only one of: {available_sr}."
        )

    # If LR data exists, require exactly one LR assembler
    if M.has_lr and lr_count == 0:
        raise WorkflowError(
            f"You didn't specify any assembler for your long-reads metagenomes and yet "
            f"you config file shows that you are not using references_mode. If you already "
            f"have your assemblies or reference fasta files, then maybe you need to add "
            f'\'"references_mode": true, and a \'"fasta_txt: "name-of-your-fasta-txt-file" '
            f"to your config file. Otherwise, if you do mean to use assembly, please set "
            f"'run: true' for one of the following available long-read assembler: {available_lr})."
        )
    if lr_count > 1:
        raise WorkflowError(
            f"Multiple long-read assemblers are enabled; enable only one of: {available_lr}."
        )

    # if an assembler is enable, but there is no matching reads:
    if not M.has_sr and sr_count == 1:
        raise WorkflowError(
            "A short-read assembler is enabled but there are no short-reads in your samples-txt"
        )
    if not M.has_lr and lr_count == 1:
        raise WorkflowError(
            "A long-read assembler is enabled but there are no long-reads in your samples-txt"
        )

# by default fastq files will be zipped after qc is done
run_gzip_fastqs = M.get_param_value_from_config(["gzip_fastqs", "run"]) == True

run_import_percent_of_reads_mapped = (
    M.get_param_value_from_config(["import_percent_of_reads_mapped", "run"]) == True
)

# convenience sets:
ASSEMBLIES = M.get_assembly_ids()
SR_READSETS = M.get_sr_readset_ids()
LR_READSETS = M.get_lr_readset_ids()
SR_ASSEMBLIES = [
    a for a in ASSEMBLIES if getattr(M, "assembly_types", {}).get(a) == "SR"
]
LR_ASSEMBLIES = [
    a for a in ASSEMBLIES if getattr(M, "assembly_types", {}).get(a) == "LR"
]


# will be used as contrained readset's wildcards for either bowtie or minimap2
SR_RS_RE = w.regex_from_ids(SR_READSETS)
LR_RS_RE = w.regex_from_ids(LR_READSETS)
# same idea but for assemblies:
SR_GRP_RE = w.regex_from_ids(SR_ASSEMBLIES)
LR_GRP_RE = w.regex_from_ids(LR_ASSEMBLIES)


ruleorder: import_percent_of_reads_mapped > import_krakenuniq_taxonomy


rule metagenomics_workflow_target_rule:
    """
The target rule for the workflow.

The final product of the workflow is an anvi'o merged profile directory
for each group
"""
    input:
        targets=M.get_metagenomics_target_files(),


# Metagenomics workflow rule modules. Keep this order: later modules rely on
# helper functions and wildcard constraints defined above or in earlier modules.
include: w.get_workflow_rule_file_path("metagenomics", "qc.smk")
include: w.get_workflow_rule_file_path("metagenomics", "read_filtering.smk")
include: w.get_workflow_rule_file_path("metagenomics", "assembly_short_reads.smk")
include: w.get_workflow_rule_file_path("metagenomics", "assembly_long_reads.smk")
include: w.get_workflow_rule_file_path("read_recruitment")
include: w.get_workflow_rule_file_path("metagenomics", "profile_postprocessing.smk")
include: w.get_workflow_rule_file_path("metagenomics", "taxonomy.smk")
include: w.get_workflow_rule_file_path("metagenomics", "binning.smk")


if "anvio/workflows/metagenomics" in str(workflow.included[0].abspath()):
    # check if all program dependencies are met. for this line to be effective,
    # there should be an initial dry run step (which is the default behavior of
    # the `WorkflowSuperClass`, so you are most likely covered).
    M.check_workflow_program_dependencies(workflow, dont_raise=True)
