# -*- coding: utf-8
import os
import json
import anvio
import argparse
import pandas as pd
import anvio.workflows as w

from anvio.errors import ConfigError
from anvio.workflows.sra_download import SRADownloadWorkflow

__copyright__ = "Copyleft 2015-2024, The Anvi'o Project (http://anvio.org/)"
__credits__ = ["mschecht"]
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "Matthew S. Schechter"
__email__ = "mschechter@uchicago.edu"


"""
This Snakemake workflow downloads, verifies, and compresses sequencing data from the NCBI Sequence Read Archive (SRA).

Software requirements:
- [The SRA toolkit](https://github.com/ncbi/sra-tools): prefetch, fasterq_dump
- [pigz](https://zlib.net/pigz/)

Workflow Steps:
---------------
1. **prefetch**: Retrieves .sra files using the SRA Toolkit's `prefetch` command.
2. **check_md5sum**: Verifies file integrity by comparing the downloaded file's MD5 hash
   against the expected hash from the NCBI `locate` API.
3. **fasterq_dump**: Converts .sra files into FASTQ format using `fasterq-dump`.
4. **pigz**: Compresses FASTQ files using parallel gzip (pigz).
5. **generate_samples_txt**: Generates `samples.txt` and `samples_single_reads.txt` files
   describing paired-end and single-end reads, respectively.

The input for this workflow is a file of SRA accessions e.g.

$ cat SRA_accession_list.txt
ERR6450080
ERR6450081
SRR5965623
ERR6450082

"""


M = SRADownloadWorkflow(argparse.Namespace(config=config))
M.init()

dirs_dict = M.dirs_dict


def rule_log(rule_name, log_file_name="log"):
    """Return a canonical workflow log path under 00_LOGS/<rule_name>/."""
    if not log_file_name.endswith(".log"):
        log_file_name = f"{log_file_name}.log"

    return os.path.join(dirs_dict["LOGS_DIR"], rule_name, log_file_name)


remove_tmp = M.get_param_value_from_config(["Remove_unzipped_SRA_files"])


rule SRA_DOWNLOAD_WORKFLOW_target_rule:
    """The rule creates all target files for the Snakefile"""
    input:
        targets=M.target_files,


# Workflow rule modules. Keep this order to preserve existing rule dependencies.
include: w.get_workflow_rule_file_path("sra_download", "download.smk")
