known_tests = {'mini'                  : ['run_component_tests_for_minimal_metagenomics.sh'],
               'metagenomics-full'     : ['run_component_tests_for_metagenomics.sh'],
               'pangenomics'           : ['run_component_tests_for_pangenomics.sh'],
               'interactive-interface' : ['run_component_tests_for_manual_interactive.sh'],
               'metabolism'            : ['run_component_tests_for_metabolism.sh'],
               'reaction-network'      : ['run_component_tests_for_reaction_network.sh'],
               'kegg-mapping'          : ['run_component_tests_for_kegg_mapping.sh'],
               'display-functions'     : ['run_component_tests_for_display_functions.sh'],
               'trnaseq'               : ['run_component_tests_for_trnaseq.sh'],
               'inversions'            : ['run_component_tests_for_inversions.sh'],
               'workflow-contigs'      : ['run_workflow_tests_for_contigs.sh'],
               'workflow-metagenomics' : ['run_workflow_tests_for_metagenomics.sh'],
               'workflow-pangenomics'  : ['run_workflow_tests_for_pangenomics.sh'],
               'workflow-phylogenomics': ['run_workflow_tests_for_phylogenomics.sh'],
               'workflow-ecophylo'     : ['run_workflow_tests_for_ecophylo.sh'],
               'database-migrations'   : ['run_migration_tests_for_ancient_anvio_databases.sh'],
               'workflow-sra-download' : ['run_workflow_tests_for_sra_download.sh'],
               'run-cazymes'           : ['run_component_tests_for_cazymes.sh'],
               'export-locus'          : ['run_component_tests_for_export_locus.sh'],
               }
