#!/usr/bin/env python
# -*- coding: utf-8

"""Migration script to convert _contigs view tables from split-keyed to contig-keyed.

Previously, the _contigs view tables stored one row per split with the parent contig's
value repeated for every split. This migration deduplicates them to store one row per
contig, reducing storage by roughly 50% for the view data.

Split names are generated by contigops.gen_split_name() as '{contig_name}_split_{%05d}'.
The suffix is '_split_' followed by one or more digits (at least 5, zero-padded). We strip
this suffix using a regex to recover the original contig name. This handles any number of
digits, so contigs with more than 99,999 splits are supported.

IMPORTANT: this migration is destructive — it drops and rebuilds the _contigs view tables.
The entire operation is wrapped in a single SQLite transaction so that a crash at any point
leaves the database unchanged.
"""

import re
import sys
import argparse

import anvio.dbinfo as dbinfo
import anvio.terminal as terminal

from anvio.errors import ConfigError

current_version, next_version = [x[1:] for x in __name__.split('_to_')]

essential_data_fields = ['std_coverage',
                         'mean_coverage',
                         'mean_coverage_Q2Q3',
                         'detection',
                         'abundance',
                         'variability']

# The split suffix appended by contigops.gen_split_name(): '_split_' + digits
SPLIT_SUFFIX_RE = re.compile(r'_split_\d+$')

run = terminal.Run()
progress = terminal.Progress()


def get_contig_name(split_name):
    """Extract the contig name from a split name by stripping the '_split_NNNNN' suffix.

    Raises ConfigError if the split name doesn't match the expected pattern.
    """

    contig_name = SPLIT_SUFFIX_RE.sub('', split_name)

    if contig_name == split_name:
        raise ConfigError(
            f"The split name '{split_name}' does not end with the expected '_split_NNNNN' suffix. "
            f"This is unexpected and the migration cannot proceed safely. Please contact the anvi'o "
            f"developers for help."
        )

    return contig_name


def migrate(db_path):
    if db_path is None:
        raise ConfigError("No database path is given.")

    profile_db_info = dbinfo.ProfileDBInfo(db_path)
    if str(profile_db_info.version) != current_version:
        raise ConfigError(
            f"The version of the provided profile database is {profile_db_info.version}, not the "
            f"required version, {current_version}, so this script cannot upgrade the database."
        )

    progress.new("Migrating")
    profile_db = profile_db_info.load_db()

    existing_tables = profile_db.get_table_names()

    # We will accumulate all SQL operations and execute them in a single transaction.
    # This way, if anything goes wrong, the database remains untouched.
    #
    # Strategy: for each _contigs table, we:
    #   1. Read all rows into Python
    #   2. Extract contig names from split names using regex (safe for any digit count)
    #   3. Validate that all splits of the same contig have identical values per layer
    #   4. Build the deduplicated rows
    #   5. Queue DROP + CREATE + INSERT operations
    #
    # All queued operations (including the version bump) are executed inside a single
    # BEGIN...COMMIT block at the end.

    queued_operations = []  # list of (sql, params_list_or_None) tuples

    for field in essential_data_fields:
        table_name = f'{field}_contigs'

        if table_name not in existing_tables:
            continue

        progress.update(f"Processing {table_name}")

        # Read all rows: each row is (entry_id, item, layer, value)
        rows = profile_db.get_all_rows_from_table(table_name)

        if not rows:
            # Empty table — nothing to deduplicate, but still recreate for schema consistency
            queued_operations.append((f'DROP TABLE IF EXISTS "{table_name}"', None))
            queued_operations.append((f'CREATE TABLE "{table_name}" (item text, layer text, value numeric)', None))
            continue

        # Build contig_name -> layer -> value mapping, validating consistency along the way
        contig_layer_values = {}  # {contig_name: {layer: value}}

        for entry_id, split_name, layer, value in rows:
            contig_name = get_contig_name(split_name)

            if contig_name not in contig_layer_values:
                contig_layer_values[contig_name] = {}

            if layer in contig_layer_values[contig_name]:
                existing_value = contig_layer_values[contig_name][layer]
                if existing_value != value:
                    raise ConfigError(
                        f"Data integrity problem in table '{table_name}': the contig '{contig_name}' "
                        f"has different values across its splits for layer '{layer}' "
                        f"(found {existing_value} and {value}). This is unexpected — all splits of "
                        f"a contig should have identical values in the _contigs view tables. The "
                        f"migration cannot proceed. Please contact the anvi'o developers for help."
                    )
            else:
                contig_layer_values[contig_name][layer] = value

        # Build the deduplicated insert rows
        new_rows = []
        for contig_name, layer_values in contig_layer_values.items():
            for layer, value in layer_values.items():
                new_rows.append((contig_name, layer, value))

        # Verify row count: number of deduplicated rows should equal
        # number of unique (contig, layer) pairs we found
        expected_count = sum(len(layers) for layers in contig_layer_values.values())
        if len(new_rows) != expected_count:
            raise ConfigError(
                f"Row count mismatch during deduplication of '{table_name}': expected {expected_count} "
                f"rows but got {len(new_rows)}. The migration cannot proceed safely."
            )

        progress.update(f"Deduplicating {table_name} ({len(rows)} rows -> {len(new_rows)} rows)")

        queued_operations.append((f'DROP TABLE IF EXISTS "{table_name}"', None))
        queued_operations.append((f'CREATE TABLE "{table_name}" (item text, layer text, value numeric)', None))
        queued_operations.append((f'INSERT INTO "{table_name}" (item, layer, value) VALUES (?, ?, ?)', new_rows))

    # Now execute everything in a single transaction
    progress.update("Applying changes in a single transaction")

    # Use the raw connection to manage the transaction manually.
    # First, commit any implicit transaction that may be open from the SELECT reads above.
    conn = profile_db.conn
    conn.commit()
    cursor = conn.cursor()

    try:
        cursor.execute('BEGIN IMMEDIATE')

        for sql, params in queued_operations:
            if params is not None:
                cursor.executemany(sql, params)
            else:
                cursor.execute(sql)

        # Update version inside the same transaction
        cursor.execute("DELETE FROM self WHERE key = 'version'")
        cursor.execute("INSERT INTO self VALUES ('version', ?)", (next_version,))

        conn.commit()
    except Exception:
        conn.rollback()
        progress.end()
        raise

    progress.update("Reclaiming disk space")
    profile_db._exec('VACUUM')

    progress.update("Done")
    profile_db.disconnect()

    progress.end()

    run.info_single(
        f"Congratulations! Your profile database is now version {next_version}. The _contigs "
        f"view tables have been deduplicated from split-keyed to contig-keyed format, "
        f"reducing redundant storage.",
        nl_after=1, nl_before=1, mc='green'
    )

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=
        f"A simple script to upgrade an anvi'o profile database from version "
        f"{current_version} to version {next_version}"
    )
    parser.add_argument(
        "profile_db",
        metavar="PROFILE_DB",
        help=f"An anvi'o profile database of version {current_version}"
    )
    args, unknown = parser.parse_known_args()

    try:
        migrate(args.profile_db)
    except ConfigError as e:
        print(e)
        sys.exit(-1)
