#!/usr/bin/env python
# -*- coding: utf-8

"""Migration script to convert _contigs view tables from split-keyed to contig-keyed.

Previously, the _contigs view tables stored one row per split with the parent contig's
value repeated for every split. This migration deduplicates them to store one row per
contig, reducing storage by roughly 50% for the view data.
"""

import re
import sys
import argparse

import anvio.dbinfo as dbinfo
import anvio.terminal as terminal

from anvio.errors import ConfigError

current_version, next_version = [x[1:] for x in __name__.split('_to_')]

essential_data_fields = ['std_coverage',
                         'mean_coverage',
                         'mean_coverage_Q2Q3',
                         'detection',
                         'abundance',
                         'variability']

run = terminal.Run()
progress = terminal.Progress()


def split_name_to_contig_name(split_name):
    """Extract the contig name from a split name.

    Split names follow the pattern '{contig_name}_split_{5-digit-number}',
    as generated by contigops.gen_split_name().
    """
    return re.sub(r'_split_\d{5}$', '', split_name)


def migrate(db_path):
    if db_path is None:
        raise ConfigError("No database path is given.")

    profile_db_info = dbinfo.ProfileDBInfo(db_path)
    if str(profile_db_info.version) != current_version:
        raise ConfigError(
            f"The version of the provided profile database is {profile_db_info.version}, not the "
            f"required version, {current_version}, so this script cannot upgrade the database."
        )

    progress.new("Migrating")
    profile_db = profile_db_info.load_db()

    for field in essential_data_fields:
        table_name = f'{field}_contigs'

        if table_name not in profile_db.get_table_names():
            continue

        progress.update(f"Deduplicating {table_name}")

        rows = profile_db.get_all_rows_from_table(table_name)

        # Deduplicate: keep one row per (contig_name, layer)
        seen = set()
        deduped_rows = []
        for _, item, layer, value in rows:
            contig_name = split_name_to_contig_name(item)
            key = (contig_name, layer)
            if key not in seen:
                seen.add(key)
                deduped_rows.append((contig_name, layer, value))

        profile_db._exec(f'DROP TABLE IF EXISTS "{table_name}"')
        profile_db._exec(f'CREATE TABLE "{table_name}" (item text, layer text, value numeric)')
        profile_db._exec_many(f'INSERT INTO "{table_name}" VALUES (?,?,?)', deduped_rows)

    progress.update("Updating version")
    profile_db.remove_meta_key_value_pair('version')
    profile_db.set_version(next_version)

    progress.update("Reclaiming disk space")
    profile_db._exec('VACUUM')

    progress.update("Committing changes")
    profile_db.disconnect()

    progress.end()

    run.info_single(
        f"Congratulations! Your profile database is now version {next_version}. The _contigs "
        f"view tables have been deduplicated from split-keyed to contig-keyed format, "
        f"reducing redundant storage.",
        nl_after=1, nl_before=1, mc='green'
    )

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=
        f"A simple script to upgrade an anvi'o profile database from version "
        f"{current_version} to version {next_version}"
    )
    parser.add_argument(
        "profile_db",
        metavar="PROFILE_DB",
        help=f"An anvi'o profile database of version {current_version}"
    )
    args, unknown = parser.parse_known_args()

    try:
        migrate(args.profile_db)
    except ConfigError as e:
        print(e)
        sys.exit(-1)
