#!/usr/bin/env python
# -*- coding: utf-8

"""Migration script to convert _contigs view tables from split-keyed to contig-keyed.

Previously, the _contigs view tables stored one row per split with the parent contig's
value repeated for every split. This migration deduplicates them to store one row per
contig, reducing storage by roughly 50% for the view data.

The deduplication is done in pure SQL for performance: the contig name is extracted by
stripping the '_split_NNNNN' suffix (always the last 12 characters of a split name,
as generated by contigops.gen_split_name()).
"""

import sys
import argparse

import anvio.dbinfo as dbinfo
import anvio.terminal as terminal

from anvio.errors import ConfigError

current_version, next_version = [x[1:] for x in __name__.split('_to_')]

essential_data_fields = ['std_coverage',
                         'mean_coverage',
                         'mean_coverage_Q2Q3',
                         'detection',
                         'abundance',
                         'variability']

run = terminal.Run()
progress = terminal.Progress()


def migrate(db_path):
    if db_path is None:
        raise ConfigError("No database path is given.")

    profile_db_info = dbinfo.ProfileDBInfo(db_path)
    if str(profile_db_info.version) != current_version:
        raise ConfigError(
            f"The version of the provided profile database is {profile_db_info.version}, not the "
            f"required version, {current_version}, so this script cannot upgrade the database."
        )

    progress.new("Migrating")
    profile_db = profile_db_info.load_db()

    for field in essential_data_fields:
        table_name = f'{field}_contigs'

        if table_name not in profile_db.get_table_names():
            continue

        progress.update(f"Deduplicating {table_name}")

        new_table_name = f'{table_name}_new'

        # Create the deduplicated table using pure SQL. The contig name is extracted
        # by stripping the last 12 characters ('_split_NNNNN') from the split name.
        # GROUP BY ensures one row per (contig_name, layer), and since all splits of
        # a contig have identical values, MIN(value) == MAX(value) == the contig value.
        profile_db._exec(f'CREATE TABLE "{new_table_name}" (item text, layer text, value numeric)')
        profile_db._exec(f'''INSERT INTO "{new_table_name}" (item, layer, value)
                             SELECT SUBSTR(item, 1, LENGTH(item) - 12), layer, MIN(value)
                             FROM "{table_name}"
                             GROUP BY SUBSTR(item, 1, LENGTH(item) - 12), layer''')
        profile_db._exec(f'DROP TABLE "{table_name}"')
        profile_db._exec(f'ALTER TABLE "{new_table_name}" RENAME TO "{table_name}"')

    progress.update("Updating version")
    profile_db.remove_meta_key_value_pair('version')
    profile_db.set_version(next_version)

    progress.update("Reclaiming disk space")
    profile_db._exec('VACUUM')

    progress.update("Committing changes")
    profile_db.disconnect()

    progress.end()

    run.info_single(
        f"Congratulations! Your profile database is now version {next_version}. The _contigs "
        f"view tables have been deduplicated from split-keyed to contig-keyed format, "
        f"reducing redundant storage.",
        nl_after=1, nl_before=1, mc='green'
    )

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=
        f"A simple script to upgrade an anvi'o profile database from version "
        f"{current_version} to version {next_version}"
    )
    parser.add_argument(
        "profile_db",
        metavar="PROFILE_DB",
        help=f"An anvi'o profile database of version {current_version}"
    )
    args, unknown = parser.parse_known_args()

    try:
        migrate(args.profile_db)
    except ConfigError as e:
        print(e)
        sys.exit(-1)
