# -*- coding: utf-8

import os
import anvio
import argparse
import pandas as pd
import anvio.workflows as w
import anvio.terminal as terminal
import anvio.filesnpaths as filesnpaths

from anvio.workflows.pangenomics import PangenomicsWorkflow

__copyright__ = "Copyleft 2015-2024, The Anvi'o Project (http://anvio.org/)"
__credits__ = []
__license__ = "GPL 3.0"
__version__ = anvio.__version__
__maintainer__ = "Alon Shaiber"
__email__ = "alon.shaiber@gmail.com"

run = terminal.Run()

this_workflow_is_inherited_by_another = (
    False
    if "anvio/workflows/pangenomics" in str(workflow.included[0].abspath())
    else True
)

if not this_workflow_is_inherited_by_another:
    M = PangenomicsWorkflow(argparse.Namespace(config=config))
    M.init()
    dirs_dict = M.dirs_dict

    # in order to generate the contigs databases we include the snakefile for the generation of contigs databases
    # include statement must come after we get an instance of PangenomicsWorkflow class
    include: w.get_workflow_snake_file_path("contigs")
    include: w.get_workflow_snake_file_path("phylogenomics")


def rule_log(rule_name, log_file_name="log"):
    """Return a canonical workflow log path under 00_LOGS/<rule_name>/."""
    if not log_file_name.endswith(".log"):
        log_file_name = f"{log_file_name}.log"

    return os.path.join(dirs_dict["LOGS_DIR"], rule_name, log_file_name)


rule pangenomics_target_rule:
    """Collect the expected pangenomics workflow outputs."""
    input:
        targets=M.get_pangenomics_target_files(),


# Workflow rule modules. Keep this order to preserve existing rule dependencies.
include: w.get_workflow_rule_file_path("pangenomics", "core.smk")


if "anvio/workflows/pangenomics" in str(workflow.included[0].abspath()):
    M.check_workflow_program_dependencies(workflow)


include: w.get_workflow_rule_file_path("pangenomics", "phylogeny.smk")
