rule anvi_reformat_fasta:
    """Reformat the FASTA file with Anvi\'o-compliant deflines."""
    input:
        fasta=M.get_input_for_anvi_reformat_fasta,
    output:
        done=touch(
            os.path.join(
                os.path.join(dirs_dict["QC_DIR"], "{sample_name}"), "REFORMAT.done"
            )
        ),
    log:
        os.path.join(
            os.path.join(dirs_dict["LOGS_DIR"], "{sample_name}"), "reformat_fasta.log"
        ),
    params:
        simplify_names=M.get_rule_param("anvi_reformat_fasta", "--simplify-names"),
    run:
        sample_name = wildcards.sample_name
        out_dir = os.path.join(dirs_dict["QC_DIR"], sample_name)
        fasta = (
            temp(os.path.join(out_dir, sample_name + "-reformatted.fasta"))
            if M.gzip_anvi_reformat_output
            else os.path.join(out_dir, sample_name + "-reformatted.fasta")
        )
        report = (
            temp(os.path.join(out_dir, sample_name + "-reformat_report.txt"))
            if M.gzip_anvi_reformat_output
            else os.path.join(out_dir, sample_name + "-reformat_report.txt")
        )
        if M.fasta_paths:
            # User provided FASTA rather than FASTQ inputs.
            if input[0].endswith(".gz"):
                decompressed_fasta = w.gunzip_file(input[0], log[0], shell)
            else:
                decompressed_fasta = input[0]
        else:
            # User provided FASTQ inputs that were merged by iu-merge-pairs.
            decompressed_fasta = os.path.join(out_dir, sample_name + "_MERGED")
            compressed_fasta = decompressed_fasta + ".gz"
            if not os.path.exists(decompressed_fasta):
                if os.path.exists(compressed_fasta):
                    w.gunzip_file(compressed_fasta, log[0], shell)
                else:
                    raise ConfigError(
                        "The workflow config file suggests that `iu_merge_pairs` was run. "
                        "However, the rule, `anvi_reformat_fasta`, could not find the file, %s, "
                        "or a compressed version of this file ending in .gz. "
                        "An input file should be generated by running the rules preceding `anvi_reformat_fasta`, "
                        "or a separate FASTA file should be supplied instead in `samples.txt`."
                        % decompressed_fasta
                    )
        shell(
            "anvi-script-reformat-fasta -o %s {params.simplify_names} --report-file %s %s >> {log} 2>&1"
            % (fasta, report, decompressed_fasta)
        )
        if (
            M.fasta_paths and input[0].endswith(".gz")
        ) or M.gzip_iu_merge_pairs_output:
            os.remove(decompressed_fasta)
        if M.gzip_anvi_reformat_output:
            if M.run_anvi_trnaseq:
                shell("gzip -c %s > %s.gz 2>>{log}" % (fasta, fasta))
            else:
                shell("gzip -f %s >> {log} 2>&1" % fasta)
            shell("gzip -f %s >> {log} 2>&1" % report)


rule all_reformatting_done:
    input:
        targets=expand(
            os.path.join(
                os.path.join(dirs_dict["QC_DIR"], "{sample_name}"), "REFORMAT.done"
            ),
            sample_name=M.sample_names,
        ),
    output:
        done=touch(os.path.join(dirs_dict["QC_DIR"], "ALL_REFORMATTING.done")),


rule anvi_trnaseq:
    input:
        source=M.get_input_for_anvi_trnaseq,
    output:
        done=touch(
            os.path.join(
                os.path.join(dirs_dict["IDENT_DIR"], "{sample_name}"), "IDENT.done"
            )
        ),
    log:
        os.path.join(
            os.path.join(dirs_dict["LOGS_DIR"], "{sample_name}"), "anvi_trnaseq.log"
        ),
    threads: M.T("anvi_trnaseq")
    params:
        overwrite_output_destinations=M.get_rule_param(
            "anvi_trnaseq", "--overwrite-output-destinations"
        ),
        description=M.get_rule_param("anvi_trnaseq", "--description"),
        write_checkpoints=M.get_rule_param("anvi_trnaseq", "--write-checkpoints"),
        load_checkpoint=M.get_rule_param("anvi_trnaseq", "--load-checkpoint"),
        feature_param_file=M.get_rule_param("anvi_trnaseq", "--feature-param-file"),
        threeprime_termini=M.get_rule_param("anvi_trnaseq", "--threeprime-termini"),
        min_length_long_fiveprime=M.get_rule_param(
            "anvi_trnaseq", "--min-length-long-fiveprime"
        ),
        min_trna_fragment_size=M.get_rule_param(
            "anvi_trnaseq", "--min-trna-fragment-size"
        ),
        agglomeration_max_mismatch_freq=M.get_rule_param(
            "anvi_trnaseq", "--agglomeration-max-mismatch-freq"
        ),
        skip_INDEL_profiling=M.get_rule_param("anvi_trnaseq", "--skip-INDEL-profiling"),
        max_indel_freq=M.get_rule_param("anvi_trnaseq", "--max-indel-freq"),
        left_indel_buffer=M.get_rule_param("anvi_trnaseq", "--left-indel-buffer"),
        right_indel_buffer=M.get_rule_param("anvi_trnaseq", "--right-indel-buffer"),
        skip_fasta_check=M.get_rule_param("anvi_trnaseq", "--skip-fasta-check"),
        profiling_chunk_size=M.get_rule_param("anvi_trnaseq", "--profiling-chunk-size"),
        alignment_target_chunk_size=M.get_rule_param(
            "anvi_trnaseq", "--alignment-target-chunk-size"
        ),
    run:
        sample_name = wildcards.sample_name
        if M.run_anvi_reformat_fasta:
            decompressed_fasta = os.path.join(
                os.path.join(dirs_dict["QC_DIR"], sample_name),
                sample_name + "-reformatted.fasta",
            )
            compressed_fasta = decompressed_fasta + ".gz"
            if not os.path.exists(decompressed_fasta):
                if os.path.exists(compressed_fasta):
                    w.gunzip_file(compressed_fasta, log[0], shell)
                else:
                    raise ConfigError(
                        "The workflow config file suggests that `anvi_reformat_fasta` was run. "
                        "However, the rule, `anvi_trnaseq`, could not find the file, %s, "
                        "or a compressed version of this file ending in .gz. "
                        "An input file should be generated by running the rules preceding `anvi_trnaseq`, "
                        "or a separate FASTA file should be supplied instead in `samples.txt`."
                        % decompressed_fasta
                    )
        else:
            if input[0].endswith(".gz"):
                decompressed_fasta = w.gunzip_file(input[0], log[0], shell)
            else:
                decompressed_fasta = input[0]
        out_dir = os.path.join(dirs_dict["IDENT_DIR"], wildcards.sample_name)
        library_num = M.sample_names.index(wildcards.sample_name)
        treatment = M.treatments[library_num]
        shell(
            "anvi-trnaseq --trnaseq-fasta %s --sample-name {wildcards.sample_name} --output-dir %s --treatment %s {params.overwrite_output_destinations} {params.description} {params.write_checkpoints} {params.load_checkpoint} {params.feature_param_file} {params.threeprime_termini} {params.min_length_long_fiveprime} {params.min_trna_fragment_size} {params.agglomeration_max_mismatch_freq} {params.skip_INDEL_profiling} {params.max_indel_freq} {params.left_indel_buffer} {params.right_indel_buffer} {params.skip_fasta_check} {params.profiling_chunk_size} {params.alignment_target_chunk_size} -T {threads} >> {log} 2>&1"
            % (decompressed_fasta, out_dir, treatment)
        )
        if (
            M.fasta_paths and input[0].endswith(".gz")
        ) or M.gzip_iu_merge_pairs_output:
            os.remove(decompressed_fasta)
