{% set version = "6.2_master" %}

package:
  name: anvio
  version: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  run:
    - anvio-minimal =={{ version }}
    - prodigal
    - mcl
    - muscle
    - hmmer
    - diamond ==0.9.14
    - blast
    - megahit
    - bowtie2
    - bwa
    - samtools
    - centrifuge
    - trimal
    - iqtree
    - fastani
    - r-base
    - r-stringi
    - r-tidyverse
    - r-magrittr
    - r-optparse
    - bioconductor
    - fasttree

test:
  commands:
    - anvi-self-test --version
    - anvi-self-test --help

about:
  home: http://merenlab.org/software/anvio/index.html
  license: GPL-3.0-or-later
  license_family: GPL3
  summary: "An interactive analysis and visualization platform for 'omics data"
  dev_url:  https://github.com/merenlab/anvio
