{% set version = "6.1_master" %}

package:
  name: anvio
  version: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  run:
    - anvio-minimal =={{ version }}
    - prodigal
    - mcl
    - muscle
    - hmmer
    - diamond=0.9.14
    - blast
    - megahit
    - bowtie2
    - bwa
    - samtools
    - centrifuge
    - trimal
    - iqtree
    - fastani
    - r
    - r-stringi
    - r-tidyverse
    - bioconductor-qvalue

test:
  commands:
    - anvi-pan-genome --help
    - anvi-script-reformat-fasta --help
    - anvi-profile --version

about:
  home: http://merenlab.org/software/anvio/index.html
  license: GPL-3.0-or-later
  license_family: GPL3
  summary: "An interactive analysis and visualization platform for 'omics data"
  dev_url:  https://github.com/merenlab/anvio
