name: Component Tests and Migrations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.suite }} (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        suite: ["metagenomics-full", "pangenomics", "inversions"]
      fail-fast: false

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Install uv & Python ${{ matrix.PYTHON_VERSION }}
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        activate-environment: "true"

    - name: "Install anvi'o from the codebase"
      shell: bash -l {0}
      run: |
        pip install uv
        uv pip install .

    - name: "Set Anvi'o interactive directory path"
      shell: bash -l {0}
      run: |
        interactive_dir=$(python -c "import site; print(site.getsitepackages()[0] + '/anvio/data/interactive')")
        echo "interactive_dir_path=$interactive_dir" >> $GITHUB_ENV

    - name: "Install npm dependencies for Anvi'o interactive interfaces"
      shell: bash -l {0}
      run: |
        cd "$interactive_dir_path"
        npm install
        cd -

    - name: "Run component tests"
      shell: bash -l {0}
      run: |
        anvi-self-test --suite ${{ matrix.suite }} --no-interactive

# the following steps cause our actions to fail on GitHub runners
# due to space limitations :/ please do not uncomment this until we
# have a solution for this :/

    #- name: "Run component tests for metabolism framework"
    #  shell: bash -l {0}
    #  run: |
    #    anvi-self-test --suite metabolism --no-interactive
    #
    #- name: "Migrate ancient anvi'o databases"
    #  shell: bash -l {0}
    #  run: |
    #    anvi-self-test --suite database-migrations
